apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertx-servicemonitor
  labels:
    app: alertx
    app.kubernetes.io/name: alertx
    # Label to allow OpenShift user-workload monitoring to pick it up
    openshift.io/user-monitoring: "true"
spec:
  selector:
    matchLabels:
      app: alertx
  endpoints:
    - port: http
      path: /healthz
      interval: 15s
      scrapeTimeout: 10s
